# Generated by Django 4.2.7 on 2023-11-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(auto_created=True, default='OFRJFVEHTFNK', max_length=15, primary_key=True, serialize=False)),
                ('typ', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
